services:

  jenkins:
    build: .
    container_name: jenkins
    restart: on-failure
    environment:
      TZ: Europe/Istanbul
      JENKINS_URL: "http://127.0.0.1:8080/"
      JENKINS_ADMIN_ID: chimp
      JENKINS_ADMIN_PASSWORD: chimp
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
